/* eslint-disable @next/next/no-page-custom-font */
/* eslint-disable @next/next/no-css-tags */
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import PreloaderHandler from "@/components/PreloaderHandler";
import type { Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Braine Digital Agency Business HTML-5 Template | Homepage 01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Stylesheets */}
        <link href="/assets/css/bootstrap.css" rel="stylesheet" />
        <link href="/assets/css/style.css" rel="stylesheet" />
        <link href="/assets/css/meanmenu.min.css" rel="stylesheet" />
        <link href="/assets/css/responsive.css" rel="stylesheet" />

        {/* Google Fonts */}
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,500;0,600;0,700;1,600;1,700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />

        {/* Favicon */}
        <link rel="shortcut icon" href="/assets/images/favicon.png" type="image/x-icon" />
        <link rel="icon" href="/assets/images/favicon.png" type="image/x-icon" />
      </head>
      <body>
        <div className="page-wrapper">
          <PreloaderHandler />

          <div className="cursor"></div>
          <div className="cursor-follower"></div>

          <div className="loader-wrap">
            <div className="preloader">
              <div className="preloader-close">x</div>
              <div id="handle-preloader" className="handle-preloader">
                <div className="animation-preloader">
                  <div className="txt-loading">
                    <span data-text-preloader="C" className="letters-loading">C</span>
                    <span data-text-preloader="I" className="letters-loading">I</span>
                    <span data-text-preloader="N" className="letters-loading">N</span>
                    <span data-text-preloader="U" className="letters-loading">U</span>
                    <span data-text-preloader="S" className="letters-loading">S</span>
                    <span data-text-preloader="E" className="letters-loading">E</span>
                    {/* <span data-text-preloader="G" className="letters-loading">G</span> */}
                  </div>
                </div>
              </div>
            </div>
          </div>
          <Header />
          {children}

          <Footer />

          <div className="progress-wrap">
            <svg className="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
              <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
            </svg>
          </div>
        </div>

        {/* JavaScript Files */}
        <Script src="/assets/js/jquery.js" strategy="beforeInteractive" />
        <Script src="/assets/js/popper.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/appear.js" strategy="afterInteractive" />
        <Script src="/assets/js/parallax.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/tilt.jquery.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.paroller.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/wow.js" strategy="afterInteractive" />
        <Script src="/assets/js/swiper.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/backtotop.js" strategy="afterInteractive" />
        <Script src="/assets/js/odometer.js" strategy="afterInteractive" />
        <Script src="/assets/js/parallax-scroll.js" strategy="afterInteractive" />
        <Script src="/assets/js/gsap.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/SplitText.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/ScrollTrigger.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/ScrollToPlugin.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/ScrollSmoother.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/touchspin.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery.marquee.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/magnific-popup.min.js" strategy="afterInteractive" />
        <Script src="/assets/js/nav-tool.js" strategy="afterInteractive" />
        <Script src="/assets/js/jquery-ui.js" strategy="afterInteractive" />
        <Script src="/assets/js/element-in-view.js" strategy="afterInteractive" />
        <Script src="/assets/js/script.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
